"""Add task assignees m2m

Revision ID: d1cd712178b1
Revises: 58f8c80e5396
Create Date: 2025-03-29 14:50:05.296189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1cd712178b1'
down_revision = '58f8c80e5396'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_assignees',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    op.alter_column('board_columns', 'order_index',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='order_index::integer')
    op.drop_constraint('tasks_assigned_to_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assigned_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('tasks_assigned_to_fkey', 'tasks', 'users', ['assigned_to'], ['id'])
    op.alter_column('board_columns', 'order_index',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='order_index::varchar')
    op.drop_table('task_assignees')
    # ### end Alembic commands ### 